version: '3.8'

services:
  db:
    image: postgres:16.4
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-django_user} -d ${POSTGRES_DB:-mvp}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    command: gunicorn cloudtalents.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - static_volume:/opt/app/cloudtalents/static
      - media_volume:/opt/app/media
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    env_file: .env
    volumes:
      - static_volume:/opt/app/cloudtalents/static
      - media_volume:/opt/app/media
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:

