name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform.yml
    with:
      action: "plan"
    secrets:
      AWS_BUDGET_CREATOR_ROLE: ${{ secrets.AWS_BUDGET_CREATOR_ROLE }}
