name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform.yml
    with:
      action: "apply"
    secrets:
      aws_budget_creator_role: ${{ secrets.AWS_BUDGET_CREATOR_ROLE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
