name: Terraform Plan

on: pull_request

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform.yml
    with:
      action: "plan"
    secrets:
      AWS_BUDGET_CREATOR_ROLE: ${{ secrets.AWS_BUDGET_CREATOR_ROLE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
