name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform.yml
    with:
      action: "apply"
    secrets:
      aws_budget_creator_role: ${{ secrets.AWS_BUDGET_CREATOR_ROLE }}
